project_id = "uonuqhtnvleeybejigsr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://the-pickleball-hub.lovable.app"
additional_redirect_urls = ["https://lovable.dev", "https://the-pickleball-hub.lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_confirmations = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false
enable_confirmations = false
test_otp = "123456"

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[edge_functions]
enabled = true
port = 54323

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[functions.send-contact-email]
verify_jwt = false