// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uonuqhtnvleeybejigsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvbnVxaHRudmxlZXliZWppZ3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDM1NTgsImV4cCI6MjA2OTExOTU1OH0.MxEdnzkTFEFIZW3jc4k-AKg4Xgf2U6X1i0B13GnT59Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});